### ISSUE TITLE
Perform regression testing of Android SDK 

### ISSUE THREAD

**Issue by YuriyVelichkoPI** [prebid/prebid-mobile-autotests#47]
## Motivation

The SDK is almost ready for release. It is time to perform regression testing.

## Objectives

Run autotests for PrebidMobile Android.

**Comment by MaksPetrukhnoPI** [comment]
Tests before release | Status | Failed Tests | Failure Message
-- | -- | -- | --
InAppBiddingBannerTests |  :white_check_mark:  |   |  
InAppBiddingInterstitialTests |  :x:  |  testAuctionRequestInterstitialMultiFormat, testAuctionRequest (In-App) | parameter ext in device is not presented
InAppBiddingVideoTests |  :x:  |  testVideoOutstream  | Watch Again Button is not displayed
InAppBiddingNativeTests |  :white_check_mark:  |   |  
InAppBiddingMRAIDTests |    |   |  
USPrivacy |  :white_check_mark:  |   |   
TCFv1 |  :white_check_mark: |   |  
CustomOpenRTB |   :white_check_mark:  |   |  
LiveRampATS |  :x:  | testLiveRampATS | parameter ext in user is not present
